version: '3.8'

services:
  mongo:
    image: mongo 
    container_name: mongo_db
    networks:
      - recipe-net
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: recipe-backend
    container_name: recipe_app_backend
    build: ./backend
    networks:
      - recipe-net
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/recipesdb
    depends_on:
      - mongo

  frontend:
    image: recipe-frontend
    container_name: recipe_app_frontend
    build: ./frontend
    networks:
      - recipe-net
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  recipe-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
    
